//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressMakerPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adresses()
        {
            this.CompaniesAdresess = new HashSet<CompaniesAdresess>();
            this.IndClientsAdresses = new HashSet<IndClientsAdresses>();
            this.WholeSalersAdresess = new HashSet<WholeSalersAdresess>();
        }
    
        public decimal IdAdress { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<decimal> HouseNumber { get; set; }
        public Nullable<decimal> FlatNumber { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompaniesAdresess> CompaniesAdresess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndClientsAdresses> IndClientsAdresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WholeSalersAdresess> WholeSalersAdresess { get; set; }
    }
}
