//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressMakerPol.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DressMakerPolEntities : DbContext
    {
        public DressMakerPolEntities()
            : base("name=DressMakerPolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_TransactionIndex_67f90f2e_4c5b_4990_863e_f67e92d2ba8c> C_TransactionIndex_67f90f2e_4c5b_4990_863e_f67e92d2ba8c { get; set; }
        public virtual DbSet<Adresses> Adresses { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<CompaniesAdresess> CompaniesAdresess { get; set; }
        public virtual DbSet<Extras> Extras { get; set; }
        public virtual DbSet<ExtrasProducts> ExtrasProducts { get; set; }
        public virtual DbSet<IndClients> IndClients { get; set; }
        public virtual DbSet<IndClientsAdresses> IndClientsAdresses { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialsProducts> MaterialsProducts { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WholeSalers> WholeSalers { get; set; }
        public virtual DbSet<WholeSalersAdresess> WholeSalersAdresess { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
