//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressMakerPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtrasProducts
    {
        public decimal IdExtra { get; set; }
        public decimal IdProduct { get; set; }
        public decimal IdExtrasProducts { get; set; }
    
        public virtual Extras Extras { get; set; }
        public virtual Products Products { get; set; }
    }
}
