//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressMakerPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsProducts
    {
        public decimal IdProduct { get; set; }
        public decimal IdMaterial { get; set; }
        public decimal IdMaterialsProducts { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
